#!/bin/bash


IMAGE=""
ARGS="-no-reboot"
TAP="-netdev tap,id=n0,ifname=tap0,script=no,downscript=no"
BRIDGENET="-device virtio-net,mac=7e:b8:7e:87:4a:ea,netdev=n0 $TAP"
USERNET="-device virtio-net,netdev=n0 -netdev user,id=n0,hostfwd=tcp::8080-:8080,hostfwd=tcp::1234-:1234" 
NET="$USERNET"
QEMU="qemu-system-x86_64"

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -q)
            shift # past argument
            QEMU="$1"
            shift # past argument
            ;;            
        -intrtrace)
            shift # past argument
            trace="$1"
            shift # past argument            
            ARGS+=" -d int -D $trace"
            ;;
        -kvm)
            ARGS+=" --enable-kvm"
            NET="$BRIDGENET"
            shift # past argument
            ;;
        -loopnet)
            NET=""
            shift # past argument
            ;;
        *)    # unknown option
            IMAGE="$1"
            shift # past argument
    esac
done


BOOT="-boot c -drive file=$IMAGE,format=raw,if=ide"
STORAGE="-drive file=$IMAGE,format=raw,if=virtio"
DISPLAY="-display none -serial stdio"
# no restart
ARGUMENTS="$BOOT $DISPLAY -m 2G -device isa-debug-exit $STORAGE $NET $ARGS"
echo "$QEMU $ARGUMENTS"
$QEMU $ARGUMENTS


