#!/bin/bash

BOOT="-boot c -drive file=$1,format=raw,if=ide"
STORAGE="-drive file=$1,format=raw,if=virtio"
TAP="-netdev tap,id=n0,ifname=tap0,script=no,downscript=no"
NET="-device virtio-net,mac=7e:b8:7e:87:4a:ea,netdev=n0 $TAP"
KVM="-enable-kvm"
DISPLAY="-display none -serial stdio"

qemu-system-x86_64 $BOOT $DISPLAY -m 2G -device isa-debug-exit $STORAGE $KVM
