ACPICA_SRCDIR= $(ACPICA_DIR)/source/components

ACPICA= \
	$(ACPICA_SRCDIR)/dispatcher/dsargs.c \
	$(ACPICA_SRCDIR)/dispatcher/dscontrol.c \
	$(ACPICA_SRCDIR)/dispatcher/dsdebug.c \
	$(ACPICA_SRCDIR)/dispatcher/dsfield.c \
	$(ACPICA_SRCDIR)/dispatcher/dsinit.c \
	$(ACPICA_SRCDIR)/dispatcher/dsmethod.c \
	$(ACPICA_SRCDIR)/dispatcher/dsmthdat.c \
	$(ACPICA_SRCDIR)/dispatcher/dsobject.c \
	$(ACPICA_SRCDIR)/dispatcher/dsopcode.c \
	$(ACPICA_SRCDIR)/dispatcher/dspkginit.c \
	$(ACPICA_SRCDIR)/dispatcher/dsutils.c \
	$(ACPICA_SRCDIR)/dispatcher/dswexec.c \
	$(ACPICA_SRCDIR)/dispatcher/dswload.c \
	$(ACPICA_SRCDIR)/dispatcher/dswload2.c \
	$(ACPICA_SRCDIR)/dispatcher/dswscope.c \
	$(ACPICA_SRCDIR)/dispatcher/dswstate.c \
	$(ACPICA_SRCDIR)/events/evevent.c \
	$(ACPICA_SRCDIR)/events/evglock.c \
	$(ACPICA_SRCDIR)/events/evgpe.c \
	$(ACPICA_SRCDIR)/events/evgpeblk.c \
	$(ACPICA_SRCDIR)/events/evgpeinit.c \
	$(ACPICA_SRCDIR)/events/evgpeutil.c \
	$(ACPICA_SRCDIR)/events/evhandler.c \
	$(ACPICA_SRCDIR)/events/evmisc.c \
	$(ACPICA_SRCDIR)/events/evregion.c \
	$(ACPICA_SRCDIR)/events/evrgnini.c \
	$(ACPICA_SRCDIR)/events/evsci.c \
	$(ACPICA_SRCDIR)/events/evxface.c \
	$(ACPICA_SRCDIR)/events/evxfevnt.c \
	$(ACPICA_SRCDIR)/events/evxfgpe.c \
	$(ACPICA_SRCDIR)/events/evxfregn.c \
	$(ACPICA_SRCDIR)/executer/exconcat.c \
	$(ACPICA_SRCDIR)/executer/exconfig.c \
	$(ACPICA_SRCDIR)/executer/exconvrt.c \
	$(ACPICA_SRCDIR)/executer/excreate.c \
	$(ACPICA_SRCDIR)/executer/exdebug.c \
	$(ACPICA_SRCDIR)/executer/exfield.c \
	$(ACPICA_SRCDIR)/executer/exfldio.c \
	$(ACPICA_SRCDIR)/executer/exmisc.c \
	$(ACPICA_SRCDIR)/executer/exmutex.c \
	$(ACPICA_SRCDIR)/executer/exnames.c \
	$(ACPICA_SRCDIR)/executer/exoparg1.c \
	$(ACPICA_SRCDIR)/executer/exoparg2.c \
	$(ACPICA_SRCDIR)/executer/exoparg3.c \
	$(ACPICA_SRCDIR)/executer/exoparg6.c \
	$(ACPICA_SRCDIR)/executer/exprep.c \
	$(ACPICA_SRCDIR)/executer/exregion.c \
	$(ACPICA_SRCDIR)/executer/exresnte.c \
	$(ACPICA_SRCDIR)/executer/exresolv.c \
	$(ACPICA_SRCDIR)/executer/exresop.c \
	$(ACPICA_SRCDIR)/executer/exserial.c \
	$(ACPICA_SRCDIR)/executer/exstore.c \
	$(ACPICA_SRCDIR)/executer/exstoren.c \
	$(ACPICA_SRCDIR)/executer/exstorob.c \
	$(ACPICA_SRCDIR)/executer/exsystem.c \
	$(ACPICA_SRCDIR)/executer/extrace.c \
	$(ACPICA_SRCDIR)/executer/exutils.c \
	$(ACPICA_SRCDIR)/hardware/hwacpi.c \
	$(ACPICA_SRCDIR)/hardware/hwesleep.c \
	$(ACPICA_SRCDIR)/hardware/hwgpe.c \
	$(ACPICA_SRCDIR)/hardware/hwpci.c \
	$(ACPICA_SRCDIR)/hardware/hwregs.c \
	$(ACPICA_SRCDIR)/hardware/hwsleep.c \
	$(ACPICA_SRCDIR)/hardware/hwvalid.c \
	$(ACPICA_SRCDIR)/hardware/hwxface.c \
	$(ACPICA_SRCDIR)/hardware/hwxfsleep.c \
	$(ACPICA_SRCDIR)/namespace/nsaccess.c \
	$(ACPICA_SRCDIR)/namespace/nsalloc.c \
	$(ACPICA_SRCDIR)/namespace/nsarguments.c \
	$(ACPICA_SRCDIR)/namespace/nsconvert.c \
	$(ACPICA_SRCDIR)/namespace/nseval.c \
	$(ACPICA_SRCDIR)/namespace/nsinit.c \
	$(ACPICA_SRCDIR)/namespace/nsload.c \
	$(ACPICA_SRCDIR)/namespace/nsnames.c \
	$(ACPICA_SRCDIR)/namespace/nsobject.c \
	$(ACPICA_SRCDIR)/namespace/nsparse.c \
	$(ACPICA_SRCDIR)/namespace/nspredef.c \
	$(ACPICA_SRCDIR)/namespace/nsprepkg.c \
	$(ACPICA_SRCDIR)/namespace/nsrepair.c \
	$(ACPICA_SRCDIR)/namespace/nsrepair2.c \
	$(ACPICA_SRCDIR)/namespace/nssearch.c \
	$(ACPICA_SRCDIR)/namespace/nsutils.c \
	$(ACPICA_SRCDIR)/namespace/nswalk.c \
	$(ACPICA_SRCDIR)/namespace/nsxfeval.c \
	$(ACPICA_SRCDIR)/namespace/nsxfname.c \
	$(ACPICA_SRCDIR)/namespace/nsxfobj.c \
	$(ACPICA_SRCDIR)/parser/psargs.c \
	$(ACPICA_SRCDIR)/parser/psloop.c \
	$(ACPICA_SRCDIR)/parser/psobject.c \
	$(ACPICA_SRCDIR)/parser/psopcode.c \
	$(ACPICA_SRCDIR)/parser/psopinfo.c \
	$(ACPICA_SRCDIR)/parser/psparse.c \
	$(ACPICA_SRCDIR)/parser/psscope.c \
	$(ACPICA_SRCDIR)/parser/pstree.c \
	$(ACPICA_SRCDIR)/parser/psutils.c \
	$(ACPICA_SRCDIR)/parser/pswalk.c \
	$(ACPICA_SRCDIR)/parser/psxface.c \
	$(ACPICA_SRCDIR)/resources/rsaddr.c \
	$(ACPICA_SRCDIR)/resources/rscalc.c \
	$(ACPICA_SRCDIR)/resources/rscreate.c \
	$(ACPICA_SRCDIR)/resources/rsinfo.c \
	$(ACPICA_SRCDIR)/resources/rsio.c \
	$(ACPICA_SRCDIR)/resources/rsirq.c \
	$(ACPICA_SRCDIR)/resources/rslist.c \
	$(ACPICA_SRCDIR)/resources/rsmemory.c \
	$(ACPICA_SRCDIR)/resources/rsmisc.c \
	$(ACPICA_SRCDIR)/resources/rsserial.c \
	$(ACPICA_SRCDIR)/resources/rsutils.c \
	$(ACPICA_SRCDIR)/resources/rsxface.c \
	$(ACPICA_SRCDIR)/tables/tbdata.c \
	$(ACPICA_SRCDIR)/tables/tbfadt.c \
	$(ACPICA_SRCDIR)/tables/tbfind.c \
	$(ACPICA_SRCDIR)/tables/tbinstal.c \
	$(ACPICA_SRCDIR)/tables/tbprint.c \
	$(ACPICA_SRCDIR)/tables/tbutils.c \
	$(ACPICA_SRCDIR)/tables/tbxface.c \
	$(ACPICA_SRCDIR)/tables/tbxfload.c \
	$(ACPICA_SRCDIR)/utilities/utaddress.c \
	$(ACPICA_SRCDIR)/utilities/utalloc.c \
	$(ACPICA_SRCDIR)/utilities/utascii.c \
	$(ACPICA_SRCDIR)/utilities/utbuffer.c \
	$(ACPICA_SRCDIR)/utilities/utcksum.c \
	$(ACPICA_SRCDIR)/utilities/utclib.c \
	$(ACPICA_SRCDIR)/utilities/utcopy.c \
	$(ACPICA_SRCDIR)/utilities/utdecode.c \
	$(ACPICA_SRCDIR)/utilities/utdelete.c \
	$(ACPICA_SRCDIR)/utilities/uterror.c \
	$(ACPICA_SRCDIR)/utilities/uteval.c \
	$(ACPICA_SRCDIR)/utilities/utexcep.c \
	$(ACPICA_SRCDIR)/utilities/uthex.c \
	$(ACPICA_SRCDIR)/utilities/utglobal.c \
	$(ACPICA_SRCDIR)/utilities/utids.c \
	$(ACPICA_SRCDIR)/utilities/utinit.c \
	$(ACPICA_SRCDIR)/utilities/utlock.c \
	$(ACPICA_SRCDIR)/utilities/utmath.c \
	$(ACPICA_SRCDIR)/utilities/utmisc.c \
	$(ACPICA_SRCDIR)/utilities/utmutex.c \
	$(ACPICA_SRCDIR)/utilities/utobject.c \
	$(ACPICA_SRCDIR)/utilities/utosi.c \
	$(ACPICA_SRCDIR)/utilities/utownerid.c \
	$(ACPICA_SRCDIR)/utilities/utpredef.c \
	$(ACPICA_SRCDIR)/utilities/utresrc.c \
	$(ACPICA_SRCDIR)/utilities/utstate.c \
	$(ACPICA_SRCDIR)/utilities/utstring.c \
	$(ACPICA_SRCDIR)/utilities/utstrsuppt.c \
	$(ACPICA_SRCDIR)/utilities/utstrtoul64.c \
	$(ACPICA_SRCDIR)/utilities/utxface.c \
	$(ACPICA_SRCDIR)/utilities/utxfinit.c \
