#define FRAME_RAX 0
#define FRAME_SYSCALL 0
#define FRAME_RBX 1
#define FRAME_RCX 2
#define FRAME_RDX 3
#define FRAME_RSI 4
#define FRAME_RDI 5
#define FRAME_RBP 6
#define FRAME_RSP 7
#define FRAME_R8  8
#define FRAME_R9  9 
#define FRAME_R10 10
#define FRAME_R11 11
#define FRAME_R12 12
#define FRAME_R13 13
#define FRAME_R14 14
#define FRAME_R15 15
#define FRAME_RIP 16
#define FRAME_FLAGS 17
#define FRAME_VECTOR 18
#define FRAME_CS 19
#define FRAME_SS 20
#define FRAME_DS 21
#define FRAME ES 22
#define FRAME_FS 23
#define FRAME_GS 24
#define FRAME_FAULT_CODE 25
#define FRAME_FAULT_HANDLER 26
#define FRAME_MAX 27
