include $(ROOT)/runtime/Makefile

VPATH += $(ROOT)/unix_process
INCLUDES += -include $(ROOT)/unix_process/unix_process.h  -I$(ROOT)/unix_process
UNIXRUNTIME = $(RUNTIME) unix_process_runtime.o

INCLUDES += -I$(ROOT)/x86_64 
