include $(ROOT)/runtime/Makefile

INCLUDES += -DUNIX_PROCESS

VPATH += $(ROOT)/unix_process
INCLUDES +=  -I$(ROOT)/unix_process
UNIXRUNTIME = $(RUNTIME) unix_process_runtime.o

INCLUDES += -I$(ROOT)/x86_64 
